custom_training_data_list = [
    ["Hello!", "Hi! How are you doing?"],
    ["I'm good. How about you?", "I'm fine, thanks."],
    ["What did you do today?", "I went for a walk in the park."],
    ["That sounds nice. How was it?", "It was very peaceful and beautiful."],
    ["Do you like going for walks often?", "Yes, I do. It helps me relax."],
    ["Have you been to any interesting places recently?", "No, not really. But I want to travel soon."],
    ["Where do you want to go?", "I think I'd like to visit Paris."],
    ["Why Paris?", "Because it's known for its art and architecture."],
    ["That's a great choice. What do you want to see there?", "I want to see the Eiffel Tower and the Louvre Museum."],
    ["Have you planned your trip yet?", "Not yet. I need to do some research first."],
    ["You should book your flights and accommodation early.", "Yes, I know. Thanks for the advice."],
    ["What kind of food do you like?", "I love Italian food, especially pizza and pasta."],
    ["Have you tried making it at home?", "Yes, but it's not as good as in a restaurant."],
    ["Do you have a favorite restaurant?", "Yes, there's a small Italian place near my house that's amazing."],
    ["What's your favorite movie?", "I really like 'The Lord of the Rings' trilogy."],
    ["Why do you like it?", "The story is so epic and the visuals are stunning."],
    ["Have you read the books?", "Yes, and I think they're even better than the movies."],
    ["Which character do you like the most?", "I like Gandalf. He's very wise and powerful."],
    ["What's your favorite hobby?", "I enjoy reading and painting."],
    ["What kind of books do you like to read?", "I like fantasy and mystery novels."],
    ["Do you have any paintings to show?", "Not yet. I'm still practicing."],
    ["How often do you paint?", "Whenever I have free time."],
    ["What kind of music do you listen to?", "I like pop and rock music."],
    ["Do you have a favorite band?", "Yes, I like Coldplay."],
    ["Which song of theirs do you like the best?", "I love 'Viva La Vida'."],
    ["Have you been to any of their concerts?", "No, but I hope to go one day."],
    ["What sports do you like?", "I like basketball and tennis."],
    ["Do you play them often?", "Not as often as I'd like. How about you?"],
    ["I like swimming. It's a great exercise.", "That's true. It's good for your body and mind."],
    ["Do you have a pet?", "Yes, I have a dog."],
    ["What's its name?", "His name is Max. He's very friendly."],
    ["Do you take him for walks often?", "Yes, every day. He loves it."],
    ["What did you do last weekend?", "I stayed at home and watched movies."],
    ["Which movies did you watch?", "I watched some action movies."],
    ["Did you enjoy them?", "Yes, they were very exciting."],
    ["What are your plans for this weekend?", "I think I'll go shopping with my friends."],
    ["That sounds fun. What do you want to buy?", "Maybe some new clothes and shoes."],
    ["Do you like online shopping or going to stores?", "I prefer going to stores. I can try things on."],
    ["What's your favorite season?", "I like autumn. The colors are beautiful."],
    ["Why do you like autumn?", "The weather is nice and not too hot or cold."],
    ["What do you usually do in autumn?", "I like to go for hikes and enjoy the scenery."],
    ["Do you have a favorite place to hike?", "Yes, there's a mountain near my town that's perfect for hiking."],
    ["How long does it take to hike there?", "It usually takes about three hours."],
    ["Do you bring something to eat and drink?", "Yes, I always bring some snacks and water."],
    ["What's your favorite subject at school?", "I like history. It's very interesting."],
    ["Why do you find history interesting?", "I like learning about the past and how things have changed over time."],
    ["Do you have a favorite historical figure?", "Yes, I like Nelson Mandela. He was a great leader."],
    ["What did he do?", "He fought for equality and justice in South Africa."],
    ["Do you like reading history books or watching documentaries?", "I like both. They give different perspectives."],
    ["What's your dream job?", "I want to be a doctor."],
    ["Why do you want to be a doctor?", "I want to help people and save lives."],
    ["How long do you think it will take to become a doctor?", "It will take many years of study and training."],
    ["Are you prepared for that?", "Yes, I am. It's my passion."],
    ["Do you like to travel alone or with others?", "I prefer to travel with others. It's more fun."],
    ["Why do you think it's more fun?", "You can share the experiences and memories with someone."],
    ["Have you ever had a bad travel experience?", "Yes, once my flight was delayed for hours."],
    ["That's not good. How did you deal with it?", "I just tried to stay patient and find something to do at the airport."],
    ["What's the best place you've ever visited?", "I think it was Bali. The beaches were amazing."],
    ["What did you do there?", "I went snorkeling and surfing."],
    ["Did you take any pictures?", "Yes, I have a lot of beautiful photos."],
    ["Do you like to take photos when you travel?", "Yes, it's a great way to remember the trip."],
    ["What kind of camera do you use?", "I have a digital SLR camera."],
    ["Do you know how to edit photos?", "A little bit. I use some basic software."],
    ["What's your favorite food to cook?", "I like to make pasta dishes."],
    ["Do you have a special recipe?", "Yes, my tomato and basil pasta is my favorite."],
    ["Can you share the recipe with me?", "Sure! First, you need to..."],
    ["Do you like to watch TV shows or movies more?", "I like both, but I watch more TV shows."],
    ["What's your favorite TV show?", "I like 'Game of Thrones'."],
    ["Why do you like it?", "The story is complex and the characters are interesting."],
    ["Have you read the books it's based on?", "No, but I want to."],
    ["Do you like to exercise in the morning or evening?", "I prefer to exercise in the evening."],
    ["Why do you like exercising in the evening?", "It helps me relax after a long day."],
    ["What kind of exercise do you do?", "I usually go for a run or do yoga."],
    ["Do you have a fitness goal?", "Yes, I want to lose some weight and get in better shape."],
    ["How do you stay motivated?", "I set small goals for myself and track my progress."],
    ["What's your favorite color?", "I like blue. It's calming."],
    ["Why do you like blue?", "It reminds me of the sky and the ocean."],
    ["Do you have a lot of blue things in your room?", "Yes, I have blue curtains and a blue bedspread."],
    ["What's your favorite animal?", "I like elephants. They're so intelligent and gentle."],
    ["Have you seen them in real life?", "Yes, at the zoo. It was an amazing experience."],
    ["Do you think we should protect wild animals?", "Yes, definitely. They're an important part of our ecosystem."],
    ["What can we do to protect them?", "We can support conservation organizations and avoid buying products that harm them."],
    ["Do you like to read books or listen to audiobooks?", "I like to read books. I enjoy the feeling of holding a book in my hands."],
    ["What's the last book you read?", "I read 'To Kill a Mockingbird'."],
    ["How did you like it?", "It was a powerful and thought-provoking book."],
    ["Do you have a favorite author?", "Yes, I like J.K. Rowling."],
    ["Why do you like her books?", "The Harry Potter series is so magical and imaginative."],
    ["Have you been to any book signings?", "No, but I'd love to go to one someday."],
    ["What's your favorite holiday?", "I like Christmas. It's a time for family and giving."],
    ["What do you do during Christmas?", "I decorate the tree, exchange gifts, and have a big dinner with my family."],
    ["Do you believe in Santa Claus?", "When I was a kid, I did. But now I know it's just a story."],
    ["What's your favorite Christmas song?", "I like 'Jingle Bells'."],
    ["Do you like to send Christmas cards?", "Yes, it's a nice way to stay in touch with friends and family."],
    ["What's your favorite game?", "I like playing chess."],
    ["Are you good at it?", "I'm okay. I still have a lot to learn."],
    ["Do you play online or with a physical board?", "Both. Online is convenient, but playing with a physical board is more fun."],
    ["Have you ever participated in a chess tournament?", "No, but I might in the future."],
    ["What do you think is the most important skill in chess?", "Strategy and patience."],
    ["Do you like to go to parties?", "Sometimes. It depends on the occasion and the people."],
    ["What kind of parties do you like?", "I like birthday parties and costume parties."],
    ["Do you like to dress up for parties?", "Yes, it's fun to come up with creative costumes."],
    ["Have you ever been to a surprise party?", "Yes, it was a lot of fun seeing the person's reaction."],
    ["What's your favorite drink?", "I like coffee. Especially cappuccino."],
    ["Do you make your own coffee at home?", "Yes, I have a coffee machine."],
    ["What's your secret to making a good cup of coffee?", "The quality of the beans and the right amount of milk and sugar."],
    ["Do you like to go to cafes?", "Yes, I enjoy the atmosphere."],
    ["What's your favorite cafe?", "There's a small one near my work that has great coffee and pastries."],
    ["Do you have a garden?", "Yes, I do. I grow some flowers and vegetables."],
    ["What kind of flowers do you have?", "I have roses and daisies."],
    ["Do you like gardening?", "Yes, it's a relaxing hobby."],
    ["How often do you take care of your garden?", "I spend some time in it every weekend."],
    ["Have you ever grown your own fruits?", "Yes, I grew some strawberries last year."],
    ["What's your favorite fruit?", "I like mangoes. They're sweet and juicy."],
    ["How was your day?", "It was quite busy but productive."],
    ["What did you do?", "I had a lot of meetings at work."],
    ["That sounds tiring. Did you get a break?", "Yes, but it was short."],
    ["Do you have any plans for the evening?", "I think I'll just relax and watch a movie."],
    ["What kind of movie do you want to watch?", "Maybe a comedy to lighten the mood."],
    ["Have you seen any good comedies lately?", "No, but I heard 'The Hangover' is hilarious."],
    ["That's a classic. Do you like going to the cinema or watching at home?",
     "I prefer watching at home. It's more comfortable."],
    ["True. Do you have any snacks for your movie night?", "I might make some popcorn."],
    ["Yum! What's your favorite flavor of popcorn?", "I like buttered popcorn the best."],
    ["That's a popular choice. How about drinks?", "I'll probably have a cold soda."],
    ["Nice. After the movie, do you plan to go to bed early?", "Maybe. It depends on how tired I am."],
    ["Well, have a great evening.", "Thanks. You too!"],
    ["Did you have a good sleep last night?", "Yes, I did. How about you?"],
    ["Not really. I had some nightmares.", "Oh no. That's not good. What were they about?"],
    ["I don't really remember. But it woke me up several times.", "That's rough. Maybe you were too stressed."],
    ["Could be. Do you have any tips for better sleep?",
     "Try to relax before bed. Maybe read a book or take a warm bath."],
    ["That sounds like a good idea. I'll give it a try.", "Hope it works for you."],
    ["Thanks. So, what are you up to today?", "I have some errands to run."],
    ["Like what?", "I need to go grocery shopping and pick up some dry cleaning."],
    ["That doesn't sound too fun.", "No, but it has to be done."],
    ["When do you think you'll finish?", "Hopefully by early afternoon."],
    ["Good luck. What are you going to make with the groceries?", "I'm thinking of making a pasta dish for dinner."],
    ["That sounds delicious. Do you have a recipe in mind?", "Yes, a simple tomato and basil pasta."],
    ["Yummy. Let me know how it turns out.", "Sure will."],
    ["Have you heard the latest song by Taylor Swift?", "No, I haven't. Is it good?"],
    ["Yes, it's very catchy. You should give it a listen.", "I will. Thanks for the recommendation."],
    ["Do you like her music in general?", "I think some of her songs are really great."],
    ["Which one is your favorite?", "I like 'Love Story' a lot."],
    ["That's a classic. Do you go to concerts often?", "Not as often as I'd like. How about you?"],
    ["I try to go to a few each year. It's such a great experience.",
     "That's awesome. Who was the best performer you've seen?"],
    ["It's hard to choose, but I really enjoyed Adele's concert.", "Wow, she has an amazing voice."],
    ["Yes, it was truly unforgettable.", "I'm jealous. Maybe I'll catch her next tour."],
    ["You should. So, what kind of music do you usually listen to besides pop?"],
    ["I also like rock and indie music."],
    ["Any specific bands or artists?"],
    ["I like Foo Fighters and Arctic Monkeys."],
    ["They're both great. Have you bought their latest albums?"],
    ["Not yet. But I'm planning to."],
    ["That's cool. Do you play any musical instruments?"],
    ["I used to play the guitar, but not anymore."],
    ["Why did you stop?"],
    ["I just didn't have enough time to practice."],
    ["That's a shame. Maybe you can pick it up again someday."],
    ["Yeah, maybe. So, what did you have for breakfast today?"],
    ["I had some toast and coffee."],
    ["Simple but classic. Do you make your own coffee?"],
    ["Yes, I have a coffee maker at home."],
    ["That's convenient. What kind of coffee do you prefer?"],
    ["I like dark roast. How about you?"],
    ["I'm more of a latte person."],
    ["Lattes are nice. Do you have a favorite coffee shop?"],
    ["There's one near my office that I like."],
    ["What do you like about it?"],
    ["The atmosphere is cozy and the staff is friendly."],
    ["That sounds great. Have you tried their pastries?"],
    ["Yes, they have some delicious muffins."],
    ["Mmm, that sounds tempting. Do you have lunch plans for today?"],
    ["I think I'll just grab a sandwich from the deli."],
    ["What kind of sandwich?"],
    ["Maybe a turkey and cheese."],
    ["That's a good choice. Do you add any condiments?"],
    ["Just some mustard and mayo."],
    ["Sounds good. What are you doing this weekend?"],
    ["I might go hiking with some friends."],
    ["That sounds like fun. Where are you going?"],
    ["We're thinking of a nearby mountain trail."],
    ["Nice. Do you need to prepare anything special?"],
    ["Yes, we need to pack enough water and snacks."],
    ["Have you checked the weather forecast?"],
    ["Yes, it looks like it'll be sunny."],
    ["That's perfect for hiking. Be safe and have a great time!"],
    ["Thanks. I'll take some pictures and show you later."],
    ["Looking forward to it. So, how's your project at work going?"],
    ["It's coming along well. We're almost done with the first phase."],
    ["That's great news. Any challenges along the way?"],
    ["Some minor setbacks, but we managed to overcome them."],
    ["Good to hear. What's next for the project?"],
    ["We need to do some testing and make a few tweaks."],
    ["I'm sure you'll handle it smoothly. How's your team working together?"],
    ["Pretty well. Everyone is contributing and communicating effectively."],
    ["That's important for a successful project. Do you have any deadlines?"],
    ["Yes, we need to finish by the end of the month."],
    ["That's coming up soon. Are you feeling pressured?"],
    ["A little, but we're on track so far."],
    ["Hope everything goes as planned. Have you had any meetings about it recently?"],
    ["Yes, we had a status update meeting yesterday."],
    ["How did that go?"],
    ["It was productive. We discussed the progress and next steps."],
    ["That's good. Well, good luck with the rest of the project."],
    ["Thanks. How about your work?"],
    ["It's okay. Just the usual tasks and deadlines."],
    ["Do you enjoy your job?"],
    ["Most of the time. There are some days that are more challenging than others."],
    ["I understand. What do you like the most about it?"],
    ["The flexibility and the opportunity to learn new things."],
    ["That's great. What about the least favorite part?"],
    ["The paperwork and bureaucracy can be a bit frustrating."],
    ["Yeah, that's common in many jobs. But at least there are some positives."],
    ["Definitely. So, have you been reading any good books lately?"],
    ["I just finished a mystery novel. It was really gripping."],
    ["What was it called?"],
    ["'The Silent Patient'. Have you heard of it?"],
    ["Yes, I have. Was the ending surprising?"],
    ["Yes, it was a total twist."],
    ["That sounds interesting. Do you have another book lined up to read?"],
    ["I'm thinking of starting a historical fiction one."],
    ["Which one?"],
    ["'The Pillars of the Earth'."],
    ["That's a classic. I hope you enjoy it."],
    ["Thanks. Do you have any reading recommendations?"],
    ["How about 'To Kill a Mockingbird'? It's a timeless classic."],
    ["I've heard of it. Maybe I'll give it a try."],
    ["You should. It's a wonderful story with important themes."],
    ["Okay. So, what's your favorite genre of movies?"],
    ["I like drama and thriller movies."],
    ["Any particular ones that stand out?"],
    ["'The Shawshank Redemption' is one of my favorites."],
    ["That's a great movie. What did you like about it?"],
    ["The powerful story of hope and friendship."],
    ["Agreed. How about thrillers?"],
    ["I thought 'Gone Girl' was really good."],
    ["That one kept me on the edge of my seat."],
    ["Yes, it was full of twists and turns."],
    ["Do you like going to the theater to watch movies or prefer streaming at home?"],
    ["I like the theater experience for big blockbusters, but for regular movies, I prefer streaming at home."],
    ["Makes sense. What about TV shows? Do you have a favorite?"],
    ["I really like 'Game of Thrones'."],
    ["That was a popular one. Who was your favorite character?"],
    ["I liked Tyrion Lannister. He was smart and had a good sense of humor."],
    ["He was a great character. Are you excited for any upcoming TV shows?"],
    ["I'm looking forward to the new season of 'Stranger Things'."],
    ["That one is always fun. Have you tried any new hobbies recently?"],
    ["I started doing yoga. It's very relaxing."],
    ["That's great. How often do you practice?"],
    ["About three times a week."],
    ["That's a good routine. Do you do it at home or in a studio?"],
    ["I do it at home for now."],
    ["Maybe you'll join a class in the future."],
    ["Maybe. How about you? Have you picked up any new hobbies?"],
    ["I started baking. It's fun to experiment with different recipes."],
    ["That sounds delicious. What's your favorite thing to bake?"],
    ["I like making chocolate chip cookies."],
    ["Yum! Do you share them with friends and family?"],
    ["Yes, they always enjoy them."],
    ["That's nice. So, what's your favorite season?"],
    ["I like autumn. The colors of the leaves are beautiful."],
    ["Me too. Do you like going for walks in the autumn?"],
    ["Yes, it's very peaceful."],
    ["What about winter? Do you like the cold and snow?"],
    ["I don't mind it as long as I'm dressed warmly."],
    ["Do you ski or snowboard?"],
    ["I've tried skiing, but I'm not very good at it."],
    ["It takes practice. How about spring? Do you like the flowers blooming?"],
    ["Yes, it's a sign of new beginnings."],
    ["And summer? Do you enjoy the beach and the sun?"],
    ["Definitely. It's a great time to relax and have fun."],
    ["Which holiday do you look forward to the most?"],
    ["I like Christmas. The atmosphere is so festive."],
    ["Me too. Do you have any special traditions?"],
    ["We always have a big family dinner and exchange gifts."],
    ["That sounds lovely. How about Halloween? Do you dress up?"],
    ["Sometimes. It's fun to be creative with costumes."],
    ["What about Thanksgiving? Do you have a big turkey dinner?"],
    ["Yes, and all the sides too."],
    ["That sounds delicious. Do you have a favorite Thanksgiving dish?"],
    ["I love the mashed potatoes and gravy."],
    ["Yum. So, what's your dream vacation destination?"],
    ["I'd love to go to Hawaii. The beaches and scenery look amazing."],
    ["That's a great choice. What would you do there?"],
    ["Relax on the beach, go snorkeling, and explore the islands."],
    ["Sounds like a perfect vacation. Have you ever been on a cruise?"],
    ["No, but I'd like to try it someday."],
    ["They can be a lot of fun. Do you prefer beach vacations or city breaks?"],
    ["I think I like a mix of both."],
    ["That's a good way to experience different things. What's your favorite city to visit?"],
    ["I really enjoyed Paris. The architecture and culture are amazing."],
    ["Yes, it's a beautiful city. Have you been to any other European cities?"],
    ["I've been to London and Rome."],
    ["How were they?"],
    ["Both were wonderful. London has so much history and Rome has the ancient ruins."],
    ["That's great. Do you have any travel plans coming up?"],
    ["Not at the moment, but I'm hoping to plan something soon."],
    ["Where do you think you'll go?"],
    ["Maybe somewhere in Asia. I've always wanted to visit Japan."],
    ["That would be an interesting trip. What do you want to see there?"],
    ["The temples, the gardens, and try the food."],
    ["Sounds like a great itinerary. Well, have a great day!"],
    ["You too. Bye!"]
]
